services:
  latexocr:
    container_name: latexocr
    build:
      context: .
      dockerfile: Dockerfile.pure-python
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Optional: only needed if you use the Azure engine
      # DOCUMENT_INTELLIGENCE_ENDPOINT: ""
      # DOCUMENT_INTELLIGENCE_SUBSCRIPTION_KEY: ""
